# Generated by Django 4.2.6 on 2024-10-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Kategoriya'),
            preserve_default=False,
        ),
    ]
