# Generated by Django 4.2.6 on 2024-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_parent_alter_images_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profession',
            field=models.CharField(max_length=100, null=True, verbose_name='Kasbi'),
        ),
    ]
